### PR TITLE
leochan.ex linkedin

### PR DESCRIPTION
**Pull request by chanleoc**
Template update due to out dated API doc

### CODE REVIEW

**Comment by odinuv** [comment]
these are rather strong changes, should it at least write to different tables? it looks like it will cause a lot of pain on existing configurations

**Comment by chanleoc** [comment]
I have switched all the updated templates from campaign_statistics to campaign_analytics which in fact is reflecting more accurately what we are extracting from the API. There is actually another endpoint in LinkedIn called AdStatistics, essentially extracting the same info but more parameters option.. will this be sufficed ?

**Comment by odinuv** [comment]
Much better, I'm thinking - how long will the old API points work? i.e. - if it's months it might be worth just adding new templates and remove the old ones only when they cease to work anyway

**Comment by chanleoc** [comment]
The old templates are no longer working =/
TBH, I have no idea when they change the parameters and it has been a while since we have customers using this component. Now we have a customer requires it and I have tested the updated templates!

**Comment by odinuv** [comment]
ic, in that case, lets get on with this :)

**Comment by odinuv** [comment]
the changes are listed here https://docs.microsoft.com/en-us/linkedin/marketing/integrations/recent-changes
i think that if you subsrcibe to linked developers, you'll get notifications

**Pull request merged**
