### PR TITLE
Zendesk Ex -- custom field fix

### PR DESCRIPTION
**Pull request by pivnicek**
Remove value from custom field PK

### CODE REVIEW

**Comment by odinuv** [comment]
isn't that a bit of a bc break?

**Comment by pivnicek** [comment]
Maybe, but the current version is broken.  That value shouldn't be a pk.

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/CQB468K63/p1595930182032800

**Comment by odinuv** [comment]
a imho by to melo jit na status

**Pull request merged**
