### PR TITLE
Updating Eatsa and SurveyMonkey extractors

### PR DESCRIPTION
**Pull request by michal-keboola**
Eatsa: wrong naming of attributes compared to the UI template
SurveyMonkey: updating auth method and dataType fields

### CODE REVIEW

**Comment by natocTo** [comment]
Hi, can I ask why is `header.authorization` part moved to template file?

**Comment by michal-keboola** [comment]
Hi,

Thank you for looking into the config. I have a working config attached (works ok in one of our projects)...should I move the header.authorization to API? I'm not that skilled in Generic config, so I might have made some workflow that works but it could have been done more elegant I guess?

[surveymonkey.txt](https://github.com/keboola/kbc-ui-templates/files/3471569/surveymonkey.txt)

**Comment by odinuv** [comment]
@michal-keboola definitely leave it in the API section if it is not necessary to move it to the config section. (you don't want to include stuff in the template, which is not supposed to be changed by the end-user)

**Comment by michal-keboola** [comment]
Ok, moved to the API config, thank you! In the meantime, I added one more extractor, so I think this pull request is redundant now and the next one should take care of all the updates (well, I think...?)

**Comment by odinuv** [comment]
i'd definitely prefer to have the procore thing separately - let's not blend everything together, also it has `https://sandbox.procore.com/vapid/"` api url, which doesn't seem right.

**Comment by michal-keboola** [comment]
Right, good point. Removing Procore...and thanks for noticing the URL...this has to be variable and I forgot it.

**Comment by odinuv** [comment]
@michal-keboola please remove the procore extractor from this PR, we have to do it in steps

**Comment by michal-keboola** [comment]
omg, I put it there for the Oauth20 and did not realize it would impact the PR. Removed!

**Pull request merged**
