### PR TITLE
Pipedrive CRM ex templates fixes

### PR DESCRIPTION
**Pull request by Matejkys**
I've made few minor fixes to the templates. Those updated/deleted fields weren't fetching any data, so it doesn't make sense to create new templates, but rather fix the old ones.

### CODE REVIEW

**Comment by odinuv** [comment]
It seems like a BC break to me having the columns deleted deal_deleted, deal_active isn't it?

**Comment by Matejkys** [comment]
Well, as it's `deal_delete` in the source, I've added `deal` to `active` as well.

**Comment by odinuv** [comment]
No, you removed deal_active and deal_deleted fields so that will break existing configurations, no?

**Comment by Matejkys** [comment]
Oh. Sorry, old PR, so it's bit fuzzy and I've looked at the files in the wrong way.
`deal_active` is non existing field. The correct is `active`:
3rd Party APIs 2021-01-28 23-34-23

`deal_deleted` is not existing as well, but the API actually returns only existing deals (`deleted = false`), so the field serve no purpose. It would just raise questions about where are the deleted deals.

**Comment by odinuv** [comment]
Ok, then, still a bit unfortunate to rename the `deal_active` to `deal`, but yeah

**Comment by Matejkys** [comment]
You mean `active` to `deal_active` :) Mmm, we can change that. And I also need to change scaffold then, as it uses `deal_deleted` in the transformation. Gosh, why everything has to be connected :)

**Comment by Matejkys** [comment]
No, let's keep the `deal_` prefix there. It's used in multiple fields. I'm not touching it any more :)

**Comment by odinuv** [comment]
No I mean't "deal_active to active" - because that's what's changing in the output  :)

image

**Comment by odinuv** [comment]
Ok, so it is a BC break then

So you have two options:
- put it back as it was
- add it as a new template (02-extendend-new)

**Comment by Matejkys** [comment]
But the `deal_active` field doesn't exist in the API. Why would we keep that in the template? Changing it will break only the UI in the config or not?

**Comment by odinuv** [comment]
yeah, only that :)

**Comment by odinuv** [comment]
so what about the deal_deleted?

**Comment by Matejkys** [comment]
Ok, let's keep the field there. But it's the same story like with `active`.

**Comment by odinuv** [comment]
image

**Pull request merged**
